/** Datos ficticios de demostración para mostrar la web completa. */

const IMG = "/burger-nick-logo.png";
const DEMO_IMAGES = {
  burgers:
    "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=82",
  combos:
    "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1200&q=82",
  sides:
    "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=1200&q=82",
  drinks:
    "https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=1200&q=82",
  desserts:
    "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=1200&q=82",
};
export const SEED_PRODUCTS = [
  // Hamburguesas
  {
    id: "nick-clasica",
    name: "Nick Clásica",
    description: "La receta que empezó todo. Jugosa, simple y perfecta.",
    ingredients: "Medallón de carne, cheddar, lechuga, tomate, cebolla, salsa Nick",
    category: "burgers",
    price: 7500,
    originalPrice: 7500,
    salePrice: null,
    imageUrl: IMG,
    available: true,
    soldOut: false,
    isNew: false,
    isTrending: true,
    isFeatured: true,
    isOnSale: false,
    sortOrder: 1,
  },
  {
    id: "nick-doble",
    name: "Burger Nick Doble",
    description: "Doble medallón, doble cheddar y el sabor que no falla.",
    ingredients: "Doble carne, doble cheddar, bacon, cebolla crispy, salsa especial",
    category: "burgers",
    price: 9500,
    originalPrice: 9500,
    salePrice: null,
    imageUrl: IMG,
    available: true,
    soldOut: false,
    isNew: false,
    isTrending: true,
    isFeatured: true,
    isOnSale: false,
    sortOrder: 2,
  },
  {
    id: "nick-picante",
    name: "Signature Fire",
    description: "Para los que bancan el calor. Picante controlado y adictivo.",
    ingredients: "Carne premium, jalapeños, cheddar, salsa chipotle, aros de cebolla",
    category: "burgers",
    price: 7900,
    originalPrice: 8900,
    salePrice: 7900,
    imageUrl: IMG,
    available: true,
    soldOut: false,
    isNew: true,
    isTrending: false,
    isFeatured: false,
    isOnSale: true,
    sortOrder: 3,
  },
  {
    id: "nick-bacon",
    name: "Bacon Crown",
    description: "Bacon crocante, queso fundido y corona de sabor.",
    ingredients: "Carne, bacon ahumado, cheddar, huevo, salsa BBQ",
    category: "burgers",
    price: 9200,
    originalPrice: 9200,
    salePrice: null,
    imageUrl: IMG,
    available: true,
    soldOut: false,
    isNew: true,
    isTrending: true,
    isFeatured: true,
    isOnSale: false,
    sortOrder: 4,
  },
  {
    id: "nick-smoked",
    name: "Smoked Champ",
    description: "Toque ahumado, cebolla caramelizada y cheddar extra.",
    ingredients: "Carne smash, cheddar, cebolla caramelizada, salsa ahumada",
    category: "burgers",
    price: 8800,
    originalPrice: 8800,
    salePrice: null,
    imageUrl: IMG,
    available: true,
    soldOut: false,
    isNew: false,
    isTrending: false,
    isFeatured: false,
    isOnSale: false,
    sortOrder: 5,
  },
  {
    id: "nick-veggie",
    name: "Green Legend",
    description: "Opción vegetariana con medallón casero y vegetales frescos.",
    ingredients: "Medallón veggie, rúcula, tomate, palta, salsa yogurt",
    category: "burgers",
    price: 8200,
    originalPrice: 8200,
    salePrice: null,
    imageUrl: IMG,
    available: true,
    soldOut: false,
    isNew: true,
    isTrending: false,
    isFeatured: false,
    isOnSale: false,
    sortOrder: 6,
  },
  {
    id: "nick-triple",
    name: "Triple Signature",
    description: "Tres medallones smash, cheddar y salsa secreta. Solo para valientes.",
    ingredients: "Triple carne smash, triple cheddar, pepinillos, salsa Nick",
    category: "burgers",
    price: 11500,
    originalPrice: 11500,
    salePrice: null,
    imageUrl: IMG,
    available: true,
    soldOut: false,
    isNew: true,
    isTrending: true,
    isFeatured: true,
    isOnSale: false,
    sortOrder: 7,
  },
  {
    id: "nick-criolla",
    name: "Criolla Deluxe",
    description: "Sabor argentino: chimichurri, cebolla y morrón asado.",
    ingredients: "Carne, chimichurri, morrón, cebolla, provolone",
    category: "burgers",
    price: 9100,
    originalPrice: 9100,
    salePrice: null,
    imageUrl: IMG,
    available: true,
    soldOut: false,
    isNew: false,
    isTrending: false,
    isFeatured: false,
    isOnSale: false,
    sortOrder: 8,
  },
  // Combos
  {
    id: "combo-clasico",
    name: "Combo Clásico",
    description: "Nick Clásica + papas + gaseosa 500ml.",
    ingredients: "Hamburguesa, papas, bebida",
    category: "combos",
    price: 11800,
    originalPrice: 12800,
    salePrice: 11800,
    imageUrl: IMG,
    available: true,
    soldOut: false,
    isNew: false,
    isTrending: true,
    isFeatured: true,
    isOnSale: true,
    sortOrder: 1,
  },
  {
    id: "combo-doble",
    name: "Combo Doble",
    description: "Nick Doble + papas cheddar + gaseosa.",
    ingredients: "Burger doble, papas cheddar, bebida",
    category: "combos",
    price: 14900,
    originalPrice: 14900,
    salePrice: null,
    imageUrl: IMG,
    available: true,
    soldOut: false,
    isNew: false,
    isTrending: true,
    isFeatured: false,
    isOnSale: false,
    sortOrder: 2,
  },
  {
    id: "combo-kids",
    name: "Combo Kids",
    description: "Mini burger + papas chicas + jugo. Ideal para peques.",
    ingredients: "Mini burger, papas, jugo",
    category: "combos",
    price: 7900,
    originalPrice: 7900,
    salePrice: null,
    imageUrl: IMG,
    available: true,
    soldOut: false,
    isNew: true,
    isTrending: false,
    isFeatured: false,
    isOnSale: false,
    sortOrder: 3,
  },
  // Acompañamientos
  {
    id: "papas-clasicas",
    name: "Papas Clásicas",
    description: "Porción generosa, crocantes por fuera y suaves por dentro.",
    ingredients: "Papas fritas, sal marina, dip a elección",
    category: "sides",
    price: 3500,
    originalPrice: 3500,
    salePrice: null,
    imageUrl: IMG,
    available: true,
    soldOut: false,
    isNew: false,
    isTrending: false,
    isFeatured: false,
    isOnSale: false,
    sortOrder: 1,
  },
  {
    id: "papas-cheddar",
    name: "Papas Cheddar Bacon",
    description: "El acompañamiento estrella. Cheddar fundido y bacon.",
    ingredients: "Papas, cheddar, bacon, cebolla de verdeo",
    category: "sides",
    price: 4800,
    originalPrice: 4800,
    salePrice: null,
    imageUrl: IMG,
    available: true,
    soldOut: false,
    isNew: false,
    isTrending: true,
    isFeatured: true,
    isOnSale: false,
    sortOrder: 2,
  },
  {
    id: "nuggets",
    name: "Nuggets Nick",
    description: "8 unidades crocantes con salsa a elección.",
    ingredients: "Pollo empanado, salsa BBQ o ketchup",
    category: "sides",
    price: 4200,
    originalPrice: 4200,
    salePrice: null,
    imageUrl: IMG,
    available: true,
    soldOut: false,
    isNew: false,
    isTrending: false,
    isFeatured: false,
    isOnSale: false,
    sortOrder: 3,
  },
  {
    id: "aros-cebolla",
    name: "Aros de Cebolla",
    description: "Porción crocante con dip ranch.",
    ingredients: "Cebolla empanada, dip ranch",
    category: "sides",
    price: 3900,
    originalPrice: 3900,
    salePrice: null,
    imageUrl: IMG,
    available: true,
    soldOut: false,
    isNew: true,
    isTrending: false,
    isFeatured: false,
    isOnSale: false,
    sortOrder: 4,
  },
  {
    id: "onion-rings-xl",
    name: "Bastones de Muzzarella",
    description: "6 bastones de muzzarella estirada.",
    ingredients: "Muzzarella, pan rallado, salsa marina",
    category: "sides",
    price: 5200,
    originalPrice: 5200,
    salePrice: null,
    imageUrl: IMG,
    available: true,
    soldOut: false,
    isNew: false,
    isTrending: false,
    isFeatured: false,
    isOnSale: false,
    sortOrder: 5,
  },
  // Bebidas
  {
    id: "bebida-gaseosa",
    name: "Gaseosa 500ml",
    description: "Coca-Cola, Sprite o Fanta bien frías.",
    ingredients: "A elección",
    category: "drinks",
    price: 1800,
    originalPrice: 1800,
    salePrice: null,
    imageUrl: IMG,
    available: true,
    soldOut: false,
    isNew: false,
    isTrending: false,
    isFeatured: false,
    isOnSale: false,
    sortOrder: 1,
  },
  {
    id: "bebida-agua",
    name: "Agua Mineral",
    description: "Con o sin gas, 500ml.",
    ingredients: "Agua mineral",
    category: "drinks",
    price: 1200,
    originalPrice: 1200,
    salePrice: null,
    imageUrl: IMG,
    available: true,
    soldOut: false,
    isNew: false,
    isTrending: false,
    isFeatured: false,
    isOnSale: false,
    sortOrder: 2,
  },
  {
    id: "milkshake",
    name: "Milkshake Nick",
    description: "Cremoso, denso y perfecto para cerrar el partido.",
    ingredients: "Helado, leche, salsa de chocolate o dulce de leche",
    category: "drinks",
    price: 4500,
    originalPrice: 4500,
    salePrice: null,
    imageUrl: IMG,
    available: true,
    soldOut: false,
    isNew: true,
    isTrending: true,
    isFeatured: false,
    isOnSale: false,
    sortOrder: 3,
  },
  {
    id: "limonada",
    name: "Limonada Casera",
    description: "Fresca, con menta y un toque de jengibre.",
    ingredients: "Limón, menta, jengibre, hielo",
    category: "drinks",
    price: 2800,
    originalPrice: 2800,
    salePrice: null,
    imageUrl: IMG,
    available: true,
    soldOut: false,
    isNew: true,
    isTrending: false,
    isFeatured: false,
    isOnSale: false,
    sortOrder: 4,
  },
  // Postres
  {
    id: "brownie",
    name: "Brownie con Helado",
    description: "Brownie caliente con bocha de helado de DDL.",
    ingredients: "Brownie, helado dulce de leche, salsa de chocolate",
    category: "desserts",
    price: 4200,
    originalPrice: 4200,
    salePrice: null,
    imageUrl: IMG,
    available: true,
    soldOut: false,
    isNew: true,
    isTrending: true,
    isFeatured: false,
    isOnSale: false,
    sortOrder: 1,
  },
  {
    id: "churros",
    name: "Churros Nick",
    description: "4 churros rellenos de dulce de leche.",
    ingredients: "Masa, dulce de leche, azúcar",
    category: "desserts",
    price: 3800,
    originalPrice: 3800,
    salePrice: null,
    imageUrl: IMG,
    available: true,
    soldOut: false,
    isNew: false,
    isTrending: false,
    isFeatured: false,
    isOnSale: false,
    sortOrder: 2,
  },
];

SEED_PRODUCTS.forEach((product) => {
  product.imageUrl = DEMO_IMAGES[product.category] || IMG;
});

export const SEED_PROMOS = [
  {
    id: "combo-pareja",
    title: "Combo Pareja",
    description: "2 Hamburguesas + Papas + 2 Bebidas. Ideal para compartir el partido.",
    imageUrl: IMG,
    badge: "Ideal para 2",
    cta: "Pedir ahora",
    link: "#menu",
    active: true,
    startDate: null,
    endDate: null,
    price: 18900,
  },
  {
    id: "combo-familiar",
    title: "Combo Familiar",
    description: "4 Hamburguesas + Papas grandes + 4 Gaseosas. Para toda la mesa.",
    imageUrl: IMG,
    badge: "Para compartir",
    cta: "Ver menú",
    link: "#menu",
    active: true,
    startDate: null,
    endDate: null,
    price: 34900,
  },
  {
    id: "happy-hour",
    title: "Happy Hour",
    description: "20% OFF en hamburguesas seleccionadas de 19 a 21 hs.",
    imageUrl: IMG,
    badge: "20% OFF",
    cta: "Aprovechá",
    link: "#menu",
    active: true,
    startDate: null,
    endDate: null,
    price: null,
  },
  {
    id: "miercoles-doble",
    title: "Miércoles Doble",
    description: "Llevás 2 Nick Clásica y pagás 1. Solo los miércoles.",
    imageUrl: IMG,
    badge: "2x1",
    cta: "Pedir ahora",
    link: "#menu",
    active: true,
    startDate: null,
    endDate: null,
    price: 7500,
  },
  {
    id: "envio-promo",
    title: "Envío bonificado",
    description: "Usá el cupón ENVIOGRATIS en pedidos desde $15.000 dentro de Apóstoles.",
    imageUrl: IMG,
    badge: "Envío gratis",
    cta: "Armá tu pedido",
    link: "#menu",
    active: true,
    startDate: null,
    endDate: null,
    price: null,
  },
];

SEED_PROMOS.forEach((promotion) => {
  promotion.imageUrl = DEMO_IMAGES.combos;
});

export const SEED_COUPONS = [
  {
    id: "coupon-nick10",
    code: "NICK10",
    type: "percent",
    value: 10,
    active: true,
    maxUses: 200,
    usedCount: 3,
    minOrderAmount: 10000,
    maxDiscount: 3000,
    freeShipping: false,
    applyToShipping: false,
    description: "10% de descuento en tu pedido",
  },
  {
    id: "coupon-bienvenida",
    code: "BIENVENIDA",
    type: "fixed",
    value: 2000,
    active: true,
    maxUses: 100,
    usedCount: 1,
    minOrderAmount: 8000,
    maxDiscount: null,
    freeShipping: false,
    applyToShipping: false,
    description: "$2000 de descuento en tu primera compra",
  },
  {
    id: "coupon-enviogratis",
    code: "ENVIOGRATIS",
    type: "fixed",
    value: 0,
    active: true,
    maxUses: 50,
    usedCount: 2,
    minOrderAmount: 15000,
    maxDiscount: null,
    freeShipping: true,
    applyToShipping: false,
    description: "Envío gratis en delivery",
  },
  {
    id: "coupon-signature15",
    code: "SIGNATURE15",
    type: "percent",
    value: 15,
    active: true,
    maxUses: 80,
    usedCount: 0,
    minOrderAmount: 12000,
    maxDiscount: 4000,
    freeShipping: false,
    applyToShipping: false,
    description: "15% OFF en hamburguesas Signature",
  },
];

/** Reservas ficticias para probar el flujo y la gestión administrativa. */
export const SEED_RESERVATIONS = [
  {
    id: "demo-reservation-01",
    name: "María Gómez",
    phone: "3760000001",
    daysAhead: 1,
    time: "21:00",
    guests: 4,
    notes: "Mesa tranquila, si es posible.",
    status: "pendiente",
  },
  {
    id: "demo-reservation-02",
    name: "Lucas Fernández",
    phone: "3760000002",
    daysAhead: 2,
    time: "22:00",
    guests: 2,
    notes: "",
    status: "confirmada",
  },
  {
    id: "demo-reservation-03",
    name: "Sofía Benítez",
    phone: "3760000003",
    daysAhead: 4,
    time: "20:30",
    guests: 6,
    notes: "Cumpleaños.",
    status: "confirmada",
  },
];

/** Clientes demo (id = teléfono normalizado). */
export const SEED_CUSTOMERS = [
  {
    id: "3760000001",
    phone: "3760000001",
    firstName: "María",
    lastName: "Gómez",
    email: "maria.gomez@example.com",
    address: "San Martín 245, Apóstoles",
    status: "Activo",
    totalOrders: 2,
    totalSpent: 46000,
  },
  {
    id: "3760000002",
    phone: "3760000002",
    firstName: "Lucas",
    lastName: "Fernández",
    email: "lucas.fernandez@example.com",
    address: "Belgrano 1180, Apóstoles",
    status: "Activo",
    totalOrders: 2,
    totalSpent: 56400,
  },
  {
    id: "3760000003",
    phone: "3760000003",
    firstName: "Valentina",
    lastName: "Ruiz",
    email: "valentina.ruiz@example.com",
    address: "Juan José Lanusse 320, Apóstoles",
    status: "Activo",
    totalOrders: 2,
    totalSpent: 66700,
  },
  {
    id: "3760000004",
    phone: "3760000004",
    firstName: "Diego",
    lastName: "Acosta",
    email: "diego.acosta@example.com",
    address: "Mitre 88, Apóstoles",
    status: "Activo",
    totalOrders: 1,
    totalSpent: 24240,
  },
  {
    id: "3760000005",
    phone: "3760000005",
    firstName: "Camila",
    lastName: "Benítez",
    email: "camila.benitez@example.com",
    address: "Retiro en el local",
    status: "Activo",
    totalOrders: 2,
    totalSpent: 31900,
  },
  {
    id: "3760000006",
    phone: "3760000006",
    firstName: "Tomás",
    lastName: "Pereyra",
    email: "tomas.pereyra@example.com",
    address: "Av. 9 de Julio 540, Apóstoles",
    status: "Activo",
    totalOrders: 2,
    totalSpent: 28470,
  },
  {
    id: "3760000007",
    phone: "3760000007",
    firstName: "Sofía",
    lastName: "Martínez",
    email: "sofia.martinez@example.com",
    address: "Sarmiento 712, Apóstoles",
    status: "Activo",
    totalOrders: 1,
    totalSpent: 14800,
  },
  {
    id: "3760000008",
    phone: "3760000008",
    firstName: "Agustín",
    lastName: "López",
    email: "agustin.lopez@example.com",
    address: "España 156, Apóstoles",
    status: "Activo",
    totalOrders: 2,
    totalSpent: 46340,
  },
];

/**
 * Pedidos demo. `daysAgo` / `hoursAgo` se convierten a Timestamp en el seed.
 * Estados: pendiente | confirmado | en_preparacion | listo | en_camino | entregado | cancelado
 */
export const SEED_ORDERS = [
  {
    id: "demo-order-01",
    orderNumber: "BN-2026-000001",
    firstName: "María",
    lastName: "Gómez",
    phone: "3760000001",
    email: "maria.gomez@example.com",
    address: "San Martín 245, Apóstoles",
    notes: "Sin cebolla en la clásica",
    paymentMethod: "Mercado Pago",
    deliveryMethod: "Delivery",
    status: "entregado",
    daysAgo: 12,
    items: [
      { productId: "nick-clasica", name: "Nick Clásica", quantity: 2, unitPrice: 7500, category: "burgers" },
      { productId: "papas-cheddar", name: "Papas Cheddar Bacon", quantity: 1, unitPrice: 4800, category: "sides" },
      { productId: "bebida-gaseosa", name: "Gaseosa 500ml", quantity: 2, unitPrice: 1800, category: "drinks" },
    ],
    subtotal: 23400,
    deliveryCost: 3000,
    discount: 0,
    total: 26400,
    couponCode: "",
    distanceKm: 2.1,
  },
  {
    id: "demo-order-02",
    orderNumber: "BN-2026-000002",
    firstName: "Lucas",
    lastName: "Fernández",
    phone: "3760000002",
    email: "lucas.fernandez@example.com",
    address: "Belgrano 1180, Apóstoles",
    notes: "",
    paymentMethod: "Transferencia",
    deliveryMethod: "Delivery",
    status: "entregado",
    daysAgo: 9,
    items: [
      { productId: "nick-doble", name: "Burger Nick Doble", quantity: 1, unitPrice: 9500, category: "burgers" },
      { productId: "nick-bacon", name: "Bacon Crown", quantity: 1, unitPrice: 9200, category: "burgers" },
      { productId: "papas-clasicas", name: "Papas Clásicas", quantity: 1, unitPrice: 3500, category: "sides" },
    ],
    subtotal: 22200,
    deliveryCost: 4500,
    discount: 2000,
    total: 24700,
    couponCode: "BIENVENIDA",
    distanceKm: 4.5,
  },
  {
    id: "demo-order-03",
    orderNumber: "BN-2026-000003",
    firstName: "Valentina",
    lastName: "Ruiz",
    phone: "3760000003",
    email: "valentina.ruiz@example.com",
    address: "Juan José Lanusse 320, Apóstoles",
    notes: "Tocar timbre 2B",
    paymentMethod: "Mercado Pago",
    deliveryMethod: "Delivery",
    status: "entregado",
    daysAgo: 6,
    items: [
      { productId: "combo-doble", name: "Combo Doble", quantity: 2, unitPrice: 14900, category: "combos" },
      { productId: "milkshake", name: "Milkshake Nick", quantity: 2, unitPrice: 4500, category: "drinks" },
    ],
    subtotal: 38800,
    deliveryCost: 0,
    discount: 0,
    total: 38800,
    couponCode: "ENVIOGRATIS",
    distanceKm: 1.2,
  },
  {
    id: "demo-order-04",
    orderNumber: "BN-2026-000004",
    firstName: "Diego",
    lastName: "Acosta",
    phone: "3760000004",
    email: "diego.acosta@example.com",
    address: "Mitre 88, Apóstoles",
    notes: "",
    paymentMethod: "Efectivo",
    deliveryMethod: "Delivery",
    status: "entregado",
    daysAgo: 4,
    items: [
      { productId: "nick-picante", name: "Signature Fire", quantity: 2, unitPrice: 7900, category: "burgers" },
      { productId: "nuggets", name: "Nuggets Nick", quantity: 1, unitPrice: 4200, category: "sides" },
      { productId: "bebida-gaseosa", name: "Gaseosa 500ml", quantity: 2, unitPrice: 1800, category: "drinks" },
    ],
    subtotal: 23600,
    deliveryCost: 3000,
    discount: 2360,
    total: 24240,
    couponCode: "NICK10",
    distanceKm: 2.8,
  },
  {
    id: "demo-order-05",
    orderNumber: "BN-2026-000005",
    firstName: "Camila",
    lastName: "Benítez",
    phone: "3760000005",
    email: "camila.benitez@example.com",
    address: "Retiro en el local",
    notes: "Paso a las 21:30",
    paymentMethod: "Tarjeta",
    deliveryMethod: "Retirar en el local",
    status: "entregado",
    daysAgo: 3,
    items: [
      { productId: "combo-clasico", name: "Combo Clásico", quantity: 1, unitPrice: 11800, category: "combos" },
      { productId: "brownie", name: "Brownie con Helado", quantity: 1, unitPrice: 4200, category: "desserts" },
    ],
    subtotal: 16000,
    deliveryCost: 0,
    discount: 0,
    total: 16000,
    couponCode: "",
    distanceKm: 0,
  },
  {
    id: "demo-order-06",
    orderNumber: "BN-2026-000006",
    firstName: "Tomás",
    lastName: "Pereyra",
    phone: "3760000006",
    email: "tomas.pereyra@example.com",
    address: "Av. 9 de Julio 540, Apóstoles",
    notes: "",
    paymentMethod: "Mercado Pago",
    deliveryMethod: "Delivery",
    status: "cancelado",
    daysAgo: 2,
    items: [
      { productId: "nick-triple", name: "Triple Signature", quantity: 1, unitPrice: 11500, category: "burgers" },
      { productId: "papas-cheddar", name: "Papas Cheddar Bacon", quantity: 1, unitPrice: 4800, category: "sides" },
    ],
    subtotal: 16300,
    deliveryCost: 3000,
    discount: 0,
    total: 19300,
    couponCode: "",
    distanceKm: 3.4,
  },
  {
    id: "demo-order-07",
    orderNumber: "BN-2026-000007",
    firstName: "Sofía",
    lastName: "Martínez",
    phone: "3760000007",
    email: "sofia.martinez@example.com",
    address: "Sarmiento 712, Apóstoles",
    notes: "",
    paymentMethod: "Transferencia",
    deliveryMethod: "Delivery",
    status: "entregado",
    daysAgo: 1,
    items: [
      { productId: "combo-clasico", name: "Combo Clásico", quantity: 1, unitPrice: 11800, category: "combos" },
    ],
    subtotal: 11800,
    deliveryCost: 3000,
    discount: 0,
    total: 14800,
    couponCode: "",
    distanceKm: 2.0,
  },
  {
    id: "demo-order-08",
    orderNumber: "BN-2026-000008",
    firstName: "Agustín",
    lastName: "López",
    phone: "3760000008",
    email: "agustin.lopez@example.com",
    address: "España 156, Apóstoles",
    notes: "Dejar en portería",
    paymentMethod: "Mercado Pago",
    deliveryMethod: "Delivery",
    status: "en_camino",
    hoursAgo: 45,
    items: [
      { productId: "nick-doble", name: "Burger Nick Doble", quantity: 2, unitPrice: 9500, category: "burgers" },
      { productId: "papas-clasicas", name: "Papas Clásicas", quantity: 2, unitPrice: 3500, category: "sides" },
      { productId: "limonada", name: "Limonada Casera", quantity: 2, unitPrice: 2800, category: "drinks" },
    ],
    subtotal: 31600,
    deliveryCost: 3000,
    discount: 3160,
    total: 31440,
    couponCode: "NICK10",
    distanceKm: 1.8,
  },
  {
    id: "demo-order-09",
    orderNumber: "BN-2026-000009",
    firstName: "Valentina",
    lastName: "Ruiz",
    phone: "3760000003",
    email: "valentina.ruiz@example.com",
    address: "Juan José Lanusse 320, Apóstoles",
    notes: "",
    paymentMethod: "Mercado Pago",
    deliveryMethod: "Delivery",
    status: "en_preparacion",
    hoursAgo: 25,
    items: [
      { productId: "nick-bacon", name: "Bacon Crown", quantity: 1, unitPrice: 9200, category: "burgers" },
      { productId: "nick-veggie", name: "Green Legend", quantity: 1, unitPrice: 8200, category: "burgers" },
      { productId: "aros-cebolla", name: "Aros de Cebolla", quantity: 1, unitPrice: 3900, category: "sides" },
      { productId: "bebida-gaseosa", name: "Gaseosa 500ml", quantity: 2, unitPrice: 1800, category: "drinks" },
    ],
    subtotal: 24900,
    deliveryCost: 3000,
    discount: 0,
    total: 27900,
    couponCode: "",
    distanceKm: 1.2,
  },
  {
    id: "demo-order-10",
    orderNumber: "BN-2026-000010",
    firstName: "María",
    lastName: "Gómez",
    phone: "3760000001",
    email: "maria.gomez@example.com",
    address: "Retiro en el local",
    notes: "Sin salsa picante",
    paymentMethod: "Efectivo",
    deliveryMethod: "Retirar en el local",
    status: "listo",
    hoursAgo: 15,
    items: [
      { productId: "combo-kids", name: "Combo Kids", quantity: 2, unitPrice: 7900, category: "combos" },
      { productId: "churros", name: "Churros Nick", quantity: 1, unitPrice: 3800, category: "desserts" },
    ],
    subtotal: 19600,
    deliveryCost: 0,
    discount: 0,
    total: 19600,
    couponCode: "",
    distanceKm: 0,
  },
  {
    id: "demo-order-11",
    orderNumber: "BN-2026-000011",
    firstName: "Lucas",
    lastName: "Fernández",
    phone: "3760000002",
    email: "lucas.fernandez@example.com",
    address: "Belgrano 1180, Apóstoles",
    notes: "Llamar al llegar",
    paymentMethod: "Transferencia",
    deliveryMethod: "Delivery",
    status: "confirmado",
    hoursAgo: 8,
    items: [
      { productId: "nick-smoked", name: "Smoked Champ", quantity: 1, unitPrice: 8800, category: "burgers" },
      { productId: "nick-criolla", name: "Criolla Deluxe", quantity: 1, unitPrice: 9100, category: "burgers" },
      { productId: "papas-cheddar", name: "Papas Cheddar Bacon", quantity: 1, unitPrice: 4800, category: "sides" },
      { productId: "milkshake", name: "Milkshake Nick", quantity: 1, unitPrice: 4500, category: "drinks" },
    ],
    subtotal: 27200,
    deliveryCost: 4500,
    discount: 0,
    total: 31700,
    couponCode: "",
    distanceKm: 4.5,
  },
  {
    id: "demo-order-12",
    orderNumber: "BN-2026-000012",
    firstName: "Tomás",
    lastName: "Pereyra",
    phone: "3760000006",
    email: "tomas.pereyra@example.com",
    address: "Av. 9 de Julio 540, Apóstoles",
    notes: "Extra cheddar si se puede",
    paymentMethod: "Mercado Pago",
    deliveryMethod: "Delivery",
    status: "pendiente",
    hoursAgo: 2,
    items: [
      { productId: "nick-clasica", name: "Nick Clásica", quantity: 1, unitPrice: 7500, category: "burgers" },
      { productId: "nick-doble", name: "Burger Nick Doble", quantity: 1, unitPrice: 9500, category: "burgers" },
      { productId: "papas-clasicas", name: "Papas Clásicas", quantity: 1, unitPrice: 3500, category: "sides" },
      { productId: "bebida-gaseosa", name: "Gaseosa 500ml", quantity: 2, unitPrice: 1800, category: "drinks" },
      { productId: "brownie", name: "Brownie con Helado", quantity: 1, unitPrice: 4200, category: "desserts" },
    ],
    subtotal: 28300,
    deliveryCost: 3000,
    discount: 2830,
    total: 28470,
    couponCode: "NICK10",
    distanceKm: 3.4,
  },
  {
    id: "demo-order-13",
    orderNumber: "BN-2026-000013",
    firstName: "Agustín",
    lastName: "López",
    phone: "3760000008",
    email: "agustin.lopez@example.com",
    address: "España 156, Apóstoles",
    notes: "",
    paymentMethod: "Mercado Pago",
    deliveryMethod: "Delivery",
    status: "pendiente",
    hoursAgo: 1,
    items: [
      { productId: "combo-doble", name: "Combo Doble", quantity: 1, unitPrice: 14900, category: "combos" },
    ],
    subtotal: 14900,
    deliveryCost: 0,
    discount: 0,
    total: 14900,
    couponCode: "ENVIOGRATIS",
    distanceKm: 1.8,
    productName: "Combo Doble",
  },
  {
    id: "demo-order-14",
    orderNumber: "BN-2026-000014",
    firstName: "Camila",
    lastName: "Benítez",
    phone: "3760000005",
    email: "camila.benitez@example.com",
    address: "Retiro en el local",
    notes: "",
    paymentMethod: "Efectivo",
    deliveryMethod: "Retirar en el local",
    status: "pendiente",
    hoursAgo: 0.5,
    items: [
      { productId: "nick-picante", name: "Signature Fire", quantity: 1, unitPrice: 7900, category: "burgers" },
      { productId: "onion-rings-xl", name: "Bastones de Muzzarella", quantity: 1, unitPrice: 5200, category: "sides" },
      { productId: "limonada", name: "Limonada Casera", quantity: 1, unitPrice: 2800, category: "drinks" },
    ],
    subtotal: 15900,
    deliveryCost: 0,
    discount: 0,
    total: 15900,
    couponCode: "",
    distanceKm: 0,
  },
];

SEED_CUSTOMERS.forEach((customer) => {
  const customerOrders = SEED_ORDERS.filter((order) => order.phone === customer.phone);
  customer.totalOrders = customerOrders.filter((order) => order.status !== "cancelado").length;
  customer.totalSpent = customerOrders
    .filter((order) => order.status !== "cancelado")
    .reduce((sum, order) => sum + Number(order.total || 0), 0);
});

export const DEMO_SETTINGS_OVERLAY = {
  payment: {
    alias: "",
    cbu: "",
    holder: "BURGER NICK",
  },
  contact: {
    whatsapp: "3765130819",
    whatsappPrimary: "3765130819",
    whatsappSecondary: "3758460155",
    whatsappCountryCode: "54",
    email: "",
    phoneMobile: "3765130819",
  },
  shipping: {
    zoneCosts: [
      { maxKm: 3.5, cost: 3000 },
      { maxKm: 5, cost: 4500 },
    ],
  },
  business: {
    name: "Burger Nick",
    slogan: "Since 2024",
    description:
      "Burger Nick nació para transformar una hamburguesa en una experiencia: ingredientes seleccionados, cocina al momento y sabor sin atajos.",
    address: "Juan José Lanusse 647",
    city: "Apóstoles",
    province: "Misiones",
    postalCode: "3350",
  },
};
